apiVersion: apps/v1
kind: Deployment
metadata:
  name: benjamintoll
spec:
  replicas: 6
  template:
    spec:
      containers:
      - name: benjamintoll
        resources:
          requests:
            cpu: 20m # 20 milliCPU / 0.02 CPU
#        livenessProbe:
#          httpGet:
#            path: /index.html
#            port: http
#          initialDelaySeconds: 5

