apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/gimlet-io/capacitor/main/deploy/k8s/rbac.yaml
  - https://raw.githubusercontent.com/gimlet-io/capacitor/main/deploy/k8s/manifest.yaml

