---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: default
spec:
  interval: 1m0s
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: applications
  path: ./config/production
  prune: true
  wait: true
  timeout: 2m0s
