---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: default
spec:
  interval: 1m0s
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: applications
      #  path: ./applications/devops/*/overlays/development
  path: ./config/development
  prune: true
  wait: true
  timeout: 2m0s
