---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  #suspend: true
  dependsOn:
    - name: infrastructure-controllers
  interval: 30s
  retryInterval: 1m0s
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: applications
  path: ./config/beta
  prune: true
  wait: true
  timeout: 2m0s

