---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: db
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
  interval: 30s
  retryInterval: 1m0s
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: applications
  path: ./applications/g00gle/db/base
  prune: true
  wait: true
  timeout: 2m0s

