namespace: default

commonAnnotations:
  onCallPager: 1-800-328-7448
  app.kubernetes.io/managed-by: "Kilgore Trout"

commonLabels:
  app: benjamintoll
  distributed: required

resources:
  - deployment.yaml
  - service.yaml
    #  - sealed-secret.yaml

#configurations:
#  - sealed-secret-config.yaml

#secretGenerator:
#  - name: sample-secret
#    type: Opaque
#    files:
#      - sealed-secret.yaml
#    options:
#      annotations:
#        config.kubernetes.io/local-config: "true"

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: benjamintoll
  path: patch.yaml

