apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: dnsutils
    count: 4

images:
- name: registry.k8s.io/e2e-test-images/jessie-dnsutils
  newName: registry.k8s.io/e2e-test-images/jessie-dnsutils
  newTag: "1.3"

